from sqlalchemy import Column, ForeignKey, Identity, Integer, Table

from . import metadata

CheckoutSessionPaymentMethodOptions.Json = Table(
    "checkout_session_payment_method_options.json",
    metadata,
    Column(
        "acss_debit",
        CheckoutAcssDebitPaymentMethodOptions,
        ForeignKey("CheckoutAcssDebitPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "affirm",
        CheckoutAffirmPaymentMethodOptions,
        ForeignKey("CheckoutAffirmPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "afterpay_clearpay",
        CheckoutAfterpayClearpayPaymentMethodOptions,
        ForeignKey("CheckoutAfterpayClearpayPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "alipay",
        CheckoutAlipayPaymentMethodOptions,
        ForeignKey("CheckoutAlipayPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "au_becs_debit",
        CheckoutAuBecsDebitPaymentMethodOptions,
        ForeignKey("CheckoutAuBecsDebitPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "bacs_debit",
        CheckoutBacsDebitPaymentMethodOptions,
        ForeignKey("CheckoutBacsDebitPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "bancontact",
        CheckoutBancontactPaymentMethodOptions,
        ForeignKey("CheckoutBancontactPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "boleto",
        CheckoutBoletoPaymentMethodOptions,
        ForeignKey("CheckoutBoletoPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "card",
        CheckoutCardPaymentMethodOptions,
        ForeignKey("CheckoutCardPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "cashapp",
        CheckoutCashappPaymentMethodOptions,
        ForeignKey("CheckoutCashappPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "customer_balance",
        CheckoutCustomerBalancePaymentMethodOptions,
        ForeignKey("CheckoutCustomerBalancePaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "eps",
        CheckoutEpsPaymentMethodOptions,
        ForeignKey("CheckoutEpsPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "fpx",
        CheckoutFpxPaymentMethodOptions,
        ForeignKey("CheckoutFpxPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "giropay",
        CheckoutGiropayPaymentMethodOptions,
        ForeignKey("CheckoutGiropayPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "grabpay",
        CheckoutGrabPayPaymentMethodOptions,
        ForeignKey("CheckoutGrabPayPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "ideal",
        CheckoutIdealPaymentMethodOptions,
        ForeignKey("CheckoutIdealPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "klarna",
        CheckoutKlarnaPaymentMethodOptions,
        ForeignKey("CheckoutKlarnaPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "konbini",
        CheckoutKonbiniPaymentMethodOptions,
        ForeignKey("CheckoutKonbiniPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "oxxo",
        CheckoutOxxoPaymentMethodOptions,
        ForeignKey("CheckoutOxxoPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "p24",
        CheckoutP24PaymentMethodOptions,
        ForeignKey("CheckoutP24PaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "paynow",
        CheckoutPaynowPaymentMethodOptions,
        ForeignKey("CheckoutPaynowPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "pix",
        CheckoutPixPaymentMethodOptions,
        ForeignKey("CheckoutPixPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "sepa_debit",
        CheckoutSepaDebitPaymentMethodOptions,
        ForeignKey("CheckoutSepaDebitPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "sofort",
        CheckoutSofortPaymentMethodOptions,
        ForeignKey("CheckoutSofortPaymentMethodOptions"),
        nullable=True,
    ),
    Column(
        "us_bank_account",
        CheckoutUsBankAccountPaymentMethodOptions,
        ForeignKey("CheckoutUsBankAccountPaymentMethodOptions"),
        nullable=True,
    ),
    Column("id", Integer, primary_key=True, server_default=Identity()),
)
__all__ = ["checkout_session_payment_method_options.json"]
