from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    ForeignKey,
    Identity,
    Integer,
    String,
    Table,
    list,
)

from stripe_openapi.account import Account
from stripe_openapi.address import Address
from stripe_openapi.application import Application
from stripe_openapi.charge import Charge
from stripe_openapi.customer import Customer
from stripe_openapi.discount import Discount
from stripe_openapi.invoice import Invoice
from stripe_openapi.quote import Quote
from stripe_openapi.shipping import Shipping
from stripe_openapi.subscription import Subscription

from . import metadata

InvoiceJson = Table(
    "invoicejson",
    metadata,
    Column(
        "account_country",
        String,
        comment="The country of the business associated with this invoice, most often the business creating the invoice",
        nullable=True,
    ),
    Column(
        "account_name",
        String,
        comment="The public name of the business associated with this invoice, most often the business creating the invoice",
        nullable=True,
    ),
    Column(
        "account_tax_ids",
        list,
        comment="The account tax IDs associated with the invoice. Only editable when the invoice is a draft",
        nullable=True,
    ),
    Column(
        "amount_due",
        Integer,
        comment="Final amount due at this time for this invoice. If the invoice's total is smaller than the minimum charge amount, for example, or if there is account credit that can be applied to the invoice, the `amount_due` may be 0. If there is a positive `starting_balance` for the invoice (the customer owes money), the `amount_due` will also take that into account. The charge that gets generated for the invoice will be for the amount specified in `amount_due`",
    ),
    Column("amount_paid", Integer, comment="The amount, in %s, that was paid"),
    Column(
        "amount_remaining",
        Integer,
        comment="The difference between amount_due and amount_paid, in %s",
    ),
    Column(
        "amount_shipping",
        Integer,
        comment="This is the sum of all the shipping amounts",
    ),
    Column(
        "application",
        Application,
        ForeignKey("DeletedApplication"),
        comment="ID of the Connect Application that created the invoice",
        nullable=True,
    ),
    Column(
        "application_fee_amount",
        Integer,
        comment="The fee in %s that will be applied to the invoice and transferred to the application owner's Stripe account when the invoice is paid",
        nullable=True,
    ),
    Column(
        "attempt_count",
        Integer,
        comment="Number of payment attempts made for this invoice, from the perspective of the payment retry schedule. Any payment attempt counts as the first attempt, and subsequently only automatic retries increment the attempt count. In other words, manual payment attempts after the first attempt do not affect the retry schedule",
    ),
    Column(
        "attempted",
        Boolean,
        comment="Whether an attempt has been made to pay the invoice. An invoice is not attempted until 1 hour after the `invoice.created` webhook, for example, so you might not want to display that invoice as unpaid to your users",
    ),
    Column(
        "auto_advance",
        Boolean,
        comment="Controls whether Stripe will perform [automatic collection](https://stripe.com/docs/billing/invoices/workflow/#auto_advance) of the invoice. When `false`, the invoice's state will not automatically advance without an explicit action",
        nullable=True,
    ),
    Column("automatic_tax", AutomaticTax, ForeignKey("AutomaticTax")),
    Column(
        "billing_reason",
        String,
        comment="Indicates the reason why the invoice was created. `subscription_cycle` indicates an invoice created by a subscription advancing into a new period. `subscription_create` indicates an invoice created due to creating a subscription. `subscription_update` indicates an invoice created due to updating a subscription. `subscription` is set for all old invoices to indicate either a change to a subscription or a period advancement. `manual` is set for all invoices unrelated to a subscription (for example: created via the invoice editor). The `upcoming` value is reserved for simulated invoices per the upcoming invoice endpoint. `subscription_threshold` indicates an invoice created due to a billing threshold being reached",
        nullable=True,
    ),
    Column(
        "charge",
        Charge,
        ForeignKey("Charge"),
        comment="ID of the latest charge generated for this invoice, if any",
        nullable=True,
    ),
    Column(
        "collection_method",
        String,
        comment="Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this invoice using the default source attached to the customer. When sending an invoice, Stripe will email this invoice to the customer with payment instructions",
    ),
    Column(
        "created",
        Integer,
        comment="Time at which the object was created. Measured in seconds since the Unix epoch",
    ),
    Column(
        "currency",
        String,
        comment="Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies)",
    ),
    Column(
        "custom_fields",
        list,
        comment="Custom fields displayed on the invoice",
        nullable=True,
    ),
    Column(
        "customer",
        Customer,
        ForeignKey("DeletedCustomer"),
        comment="The ID of the customer who will be billed",
        nullable=True,
    ),
    Column(
        "customer_address",
        Address,
        ForeignKey("Address"),
        comment="The customer's address. Until the invoice is finalized, this field will equal `customer.address`. Once the invoice is finalized, this field will no longer be updated",
        nullable=True,
    ),
    Column(
        "customer_email",
        String,
        comment="The customer's email. Until the invoice is finalized, this field will equal `customer.email`. Once the invoice is finalized, this field will no longer be updated",
        nullable=True,
    ),
    Column(
        "customer_name",
        String,
        comment="The customer's name. Until the invoice is finalized, this field will equal `customer.name`. Once the invoice is finalized, this field will no longer be updated",
        nullable=True,
    ),
    Column(
        "customer_phone",
        String,
        comment="The customer's phone number. Until the invoice is finalized, this field will equal `customer.phone`. Once the invoice is finalized, this field will no longer be updated",
        nullable=True,
    ),
    Column(
        "customer_shipping",
        Shipping,
        ForeignKey("Shipping"),
        comment="The customer's shipping information. Until the invoice is finalized, this field will equal `customer.shipping`. Once the invoice is finalized, this field will no longer be updated",
        nullable=True,
    ),
    Column(
        "customer_tax_exempt",
        String,
        comment="The customer's tax exempt status. Until the invoice is finalized, this field will equal `customer.tax_exempt`. Once the invoice is finalized, this field will no longer be updated",
        nullable=True,
    ),
    Column(
        "customer_tax_ids",
        list,
        comment="The customer's tax IDs. Until the invoice is finalized, this field will contain the same tax IDs as `customer.tax_ids`. Once the invoice is finalized, this field will no longer be updated",
        nullable=True,
    ),
    Column(
        "default_payment_method",
        PaymentMethod,
        ForeignKey("PaymentMethod"),
        comment="ID of the default payment method for the invoice. It must belong to the customer associated with the invoice. If not set, defaults to the subscription's default payment method, if any, or to the default payment method in the customer's invoice settings",
        nullable=True,
    ),
    Column(
        "default_source",
        PaymentSource,
        ForeignKey("PaymentSource"),
        comment="ID of the default payment source for the invoice. It must belong to the customer associated with the invoice and be in a chargeable state. If not set, defaults to the subscription's default source, if any, or to the customer's default source",
        nullable=True,
    ),
    Column(
        "default_tax_rates",
        list,
        comment="The tax rates applied to this invoice, if any",
    ),
    Column(
        "description",
        String,
        comment="An arbitrary string attached to the object. Often useful for displaying to users. Referenced as 'memo' in the Dashboard",
        nullable=True,
    ),
    Column(
        "discount",
        Discount,
        ForeignKey("Discount"),
        comment="Describes the current discount applied to this invoice, if there is one. Not populated if there are multiple discounts",
        nullable=True,
    ),
    Column(
        "discounts",
        list,
        comment="The discounts applied to the invoice. Line item discounts are applied before invoice discounts. Use `expand[]=discounts` to expand each discount",
        nullable=True,
    ),
    Column(
        "due_date",
        Integer,
        comment="The date on which payment for this invoice is due. This value will be `null` for invoices where `collection_method=charge_automatically`",
        nullable=True,
    ),
    Column(
        "ending_balance",
        Integer,
        comment="Ending customer balance after the invoice is finalized. Invoices are finalized approximately an hour after successful webhook delivery or when payment collection is attempted for the invoice. If the invoice has not been finalized yet, this will be null",
        nullable=True,
    ),
    Column("footer", String, comment="Footer displayed on the invoice", nullable=True),
    Column(
        "from_invoice",
        InvoicesFromInvoice,
        ForeignKey("InvoicesFromInvoice"),
        comment="Details of the invoice that was cloned. See the [revision documentation](https://stripe.com/docs/invoicing/invoice-revisions) for more details",
        nullable=True,
    ),
    Column(
        "hosted_invoice_url",
        String,
        comment="The URL for the hosted invoice page, which allows customers to view and pay an invoice. If the invoice has not been finalized yet, this will be null",
        nullable=True,
    ),
    Column("id", Integer, primary_key=True, server_default=Identity()),
    Column(
        "invoice_pdf",
        String,
        comment="The link to download the PDF for the invoice. If the invoice has not been finalized yet, this will be null",
        nullable=True,
    ),
    Column(
        "last_finalization_error",
        ApiErrors,
        ForeignKey("ApiErrors"),
        comment="The error encountered during the previous attempt to finalize the invoice. This field is cleared when the invoice is successfully finalized",
        nullable=True,
    ),
    Column(
        "latest_revision",
        Invoice,
        ForeignKey("Invoice"),
        comment="The ID of the most recent non-draft revision of this invoice",
        nullable=True,
    ),
    Column(
        "lines",
        JSON,
        comment="The individual line items that make up the invoice. `lines` is sorted as follows: (1) pending invoice items (including prorations) in reverse chronological order, (2) subscription items in reverse chronological order, and (3) invoice items added after invoice creation in chronological order",
    ),
    Column(
        "livemode",
        Boolean,
        comment="Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode",
    ),
    Column(
        "metadata",
        JSON,
        comment="Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format",
        nullable=True,
    ),
    Column(
        "next_payment_attempt",
        Integer,
        comment="The time at which payment will next be attempted. This value will be `null` for invoices where `collection_method=send_invoice`",
        nullable=True,
    ),
    Column(
        "number",
        String,
        comment="A unique, identifying string that appears on emails sent to the customer for this invoice. This starts with the customer's unique invoice_prefix if it is specified",
        nullable=True,
    ),
    Column(
        "object",
        String,
        comment="String representing the object's type. Objects of the same type share the same value",
    ),
    Column(
        "on_behalf_of",
        Account,
        ForeignKey("Account"),
        comment="The account (if any) for which the funds of the invoice payment are intended. If set, the invoice will be presented with the branding and support information of the specified account. See the [Invoices with Connect](https://stripe.com/docs/billing/invoices/connect) documentation for details",
        nullable=True,
    ),
    Column(
        "paid",
        Boolean,
        comment="Whether payment was successfully collected for this invoice. An invoice can be paid (most commonly) with a charge or with credit from the customer's account balance",
    ),
    Column(
        "paid_out_of_band",
        Boolean,
        comment="Returns true if the invoice was manually marked paid, returns false if the invoice hasn't been paid yet or was paid on Stripe",
    ),
    Column(
        "payment_intent",
        PaymentIntent,
        ForeignKey("PaymentIntent"),
        comment="The PaymentIntent associated with this invoice. The PaymentIntent is generated when the invoice is finalized, and can then be used to pay the invoice. Note that voiding an invoice will cancel the PaymentIntent",
        nullable=True,
    ),
    Column(
        "payment_settings",
        InvoicesPaymentSettings,
        ForeignKey("InvoicesPaymentSettings"),
    ),
    Column(
        "period_end",
        Integer,
        comment="End of the usage period during which invoice items were added to this invoice",
    ),
    Column(
        "period_start",
        Integer,
        comment="Start of the usage period during which invoice items were added to this invoice",
    ),
    Column(
        "post_payment_credit_notes_amount",
        Integer,
        comment="Total amount of all post-payment credit notes issued for this invoice",
    ),
    Column(
        "pre_payment_credit_notes_amount",
        Integer,
        comment="Total amount of all pre-payment credit notes issued for this invoice",
    ),
    Column(
        "quote",
        Quote,
        ForeignKey("Quote"),
        comment="The quote this invoice was generated from",
        nullable=True,
    ),
    Column(
        "receipt_number",
        String,
        comment="This is the transaction number that appears on email receipts sent for this invoice",
        nullable=True,
    ),
    Column(
        "rendering_options",
        InvoiceSettingRenderingOptions,
        ForeignKey("InvoiceSettingRenderingOptions"),
        comment="Options for invoice PDF rendering",
        nullable=True,
    ),
    Column(
        "shipping_cost",
        InvoicesShippingCost,
        ForeignKey("InvoicesShippingCost"),
        comment="The details of the cost of shipping, including the ShippingRate applied on the invoice",
        nullable=True,
    ),
    Column(
        "shipping_details",
        Shipping,
        ForeignKey("Shipping"),
        comment="Shipping details for the invoice. The Invoice PDF will use the `shipping_details` value if it is set, otherwise the PDF will render the shipping address from the customer",
        nullable=True,
    ),
    Column(
        "starting_balance",
        Integer,
        comment="Starting customer balance before the invoice is finalized. If the invoice has not been finalized yet, this will be the current customer balance. For revision invoices, this also includes any customer balance that was applied to the original invoice",
    ),
    Column(
        "statement_descriptor",
        String,
        comment="Extra information about an invoice for the customer's credit card statement",
        nullable=True,
    ),
    Column(
        "status",
        String,
        comment="The status of the invoice, one of `draft`, `open`, `paid`, `uncollectible`, or `void`. [Learn more](https://stripe.com/docs/billing/invoices/workflow#workflow-overview)",
        nullable=True,
    ),
    Column(
        "status_transitions",
        InvoicesStatusTransitions,
        ForeignKey("InvoicesStatusTransitions"),
    ),
    Column(
        "subscription",
        Subscription,
        ForeignKey("Subscription"),
        comment="The subscription that this invoice was prepared for, if any",
        nullable=True,
    ),
    Column(
        "subscription_proration_date",
        Integer,
        comment="Only set for upcoming invoices that preview prorations. The time used to calculate prorations",
        nullable=True,
    ),
    Column(
        "subtotal",
        Integer,
        comment="Total of all subscriptions, invoice items, and prorations on the invoice before any invoice level discount or exclusive tax is applied. Item discounts are already incorporated",
    ),
    Column(
        "subtotal_excluding_tax",
        Integer,
        comment="The integer amount in %s representing the subtotal of the invoice before any invoice level discount or tax is applied. Item discounts are already incorporated",
        nullable=True,
    ),
    Column(
        "tax",
        Integer,
        comment="The amount of tax on this invoice. This is the sum of all the tax amounts on this invoice",
        nullable=True,
    ),
    Column(
        "test_clock",
        Test_Helpers__TestClock,
        ForeignKey("Test_Helpers__TestClock"),
        comment="ID of the test clock this invoice belongs to",
        nullable=True,
    ),
    Column(
        "threshold_reason",
        InvoiceThresholdReason,
        ForeignKey("InvoiceThresholdReason"),
        nullable=True,
    ),
    Column("total", Integer, comment="Total after discounts and taxes"),
    Column(
        "total_discount_amounts",
        list,
        comment="The aggregate amounts calculated per discount across all line items",
        nullable=True,
    ),
    Column(
        "total_excluding_tax",
        Integer,
        comment="The integer amount in %s representing the total amount of the invoice including all discounts but excluding all tax",
        nullable=True,
    ),
    Column(
        "total_tax_amounts",
        list,
        comment="The aggregate amounts calculated per tax rate for all line items",
    ),
    Column(
        "transfer_data",
        InvoiceTransferData,
        ForeignKey("InvoiceTransferData"),
        comment="The account (if any) the payment will be attributed to for tax reporting, and where funds from the payment will be transferred to for the invoice",
        nullable=True,
    ),
    Column(
        "webhooks_delivered_at",
        Integer,
        comment="Invoices are automatically paid or sent 1 hour after webhooks are delivered, or until all webhook delivery attempts have [been exhausted](https://stripe.com/docs/billing/webhooks#understand). This field tracks the time when webhooks for this invoice were successfully delivered. If the invoice had no webhooks to deliver, this will be set while the invoice is being created",
        nullable=True,
    ),
)
__all__ = ["invoice.json"]
