from sqlalchemy import Column, Identity, Integer, Table

from . import metadata

InvoiceSettingSubscriptionScheduleSettingJson = Table(
    "invoice_setting_subscription_schedule_settingjson",
    metadata,
    Column(
        "days_until_due",
        Integer,
        comment="Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`",
        nullable=True,
    ),
    Column("id", Integer, primary_key=True, server_default=Identity()),
)
__all__ = ["invoice_setting_subscription_schedule_setting.json"]
