from sqlalchemy import Column, String, Table

from . import metadata

PaymentMethodDetailsFpx.Json = Table(
    "payment_method_details_fpx.json",
    metadata,
    Column(
        "account_holder_type",
        String,
        comment="Account holder type, if provided. Can be one of `individual` or `company`",
        nullable=True,
    ),
    Column(
        "bank",
        String,
        comment="The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`",
    ),
    Column(
        "transaction_id",
        String,
        comment="Unique transaction id generated by FPX for every request from the merchant",
        nullable=True,
        primary_key=True,
    ),
)
__all__ = ["payment_method_details_fpx.json"]
