from sqlalchemy import Column, String, Table

from . import metadata

PaymentMethodDetailsPix.Json = Table(
    "payment_method_details_pix.json",
    metadata,
    Column(
        "bank_transaction_id",
        String,
        comment="Unique transaction id generated by BCB",
        nullable=True,
        primary_key=True,
    ),
)
__all__ = ["payment_method_details_pix.json"]
