from sqlalchemy import Column, Identity, Integer, String, Table

from . import metadata

PaymentMethodDetailsPromptpayJson = Table(
    "payment_method_details_promptpayjson",
    metadata,
    Column(
        "reference",
        String,
        comment="Bill reference generated by PromptPay",
        nullable=True,
    ),
    Column("id", Integer, primary_key=True, server_default=Identity()),
)
__all__ = ["payment_method_details_promptpay.json"]
