from sqlalchemy import Column, Identity, Integer, String, Table

from . import metadata

PaymentMethodDetailsInteracPresentReceiptJson = Table(
    "payment_method_details_interac_present_receiptjson",
    metadata,
    Column(
        "account_type",
        String,
        comment="The type of account being debited or credited",
        nullable=True,
    ),
    Column(
        "application_cryptogram",
        String,
        comment="EMV tag 9F26, cryptogram generated by the integrated circuit chip",
        nullable=True,
    ),
    Column(
        "application_preferred_name",
        String,
        comment="Mnenomic of the Application Identifier",
        nullable=True,
    ),
    Column(
        "authorization_code",
        String,
        comment="Identifier for this transaction",
        nullable=True,
    ),
    Column(
        "authorization_response_code",
        String,
        comment="EMV tag 8A. A code returned by the card issuer",
        nullable=True,
    ),
    Column(
        "cardholder_verification_method",
        String,
        comment="How the cardholder verified ownership of the card",
        nullable=True,
    ),
    Column(
        "dedicated_file_name",
        String,
        comment="EMV tag 84. Similar to the application identifier stored on the integrated circuit chip",
        nullable=True,
    ),
    Column(
        "terminal_verification_results",
        String,
        comment="The outcome of a series of EMV functions performed by the card reader",
        nullable=True,
    ),
    Column(
        "transaction_status_information",
        String,
        comment="An indication of various EMV functions performed during the transaction",
        nullable=True,
    ),
    Column("id", Integer, primary_key=True, server_default=Identity()),
)
__all__ = ["payment_method_details_interac_present_receipt.json"]
