from sqlalchemy import JSON, Column, ForeignKey, String, Table

from . import metadata

PaymentIntentNextActionJson = Table(
    "payment_intent_next_actionjson",
    metadata,
    Column(
        "alipay_handle_redirect",
        PaymentIntentNextActionAlipayHandleRedirect,
        ForeignKey("PaymentIntentNextActionAlipayHandleRedirect"),
        nullable=True,
    ),
    Column(
        "boleto_display_details",
        PaymentIntentNextActionBoleto,
        ForeignKey("PaymentIntentNextActionBoleto"),
        nullable=True,
    ),
    Column(
        "card_await_notification",
        PaymentIntentNextActionCardAwaitNotification,
        ForeignKey("PaymentIntentNextActionCardAwaitNotification"),
        nullable=True,
    ),
    Column(
        "cashapp_handle_redirect_or_display_qr_code",
        PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode,
        ForeignKey("PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode"),
        nullable=True,
    ),
    Column(
        "display_bank_transfer_instructions",
        PaymentIntentNextActionDisplayBankTransferInstructions,
        ForeignKey("PaymentIntentNextActionDisplayBankTransferInstructions"),
        nullable=True,
    ),
    Column(
        "konbini_display_details",
        PaymentIntentNextActionKonbini,
        ForeignKey("PaymentIntentNextActionKonbini"),
        nullable=True,
    ),
    Column(
        "oxxo_display_details",
        PaymentIntentNextActionDisplayOxxoDetails,
        ForeignKey("PaymentIntentNextActionDisplayOxxoDetails"),
        nullable=True,
    ),
    Column(
        "paynow_display_qr_code",
        PaymentIntentNextActionPaynowDisplayQrCode,
        ForeignKey("PaymentIntentNextActionPaynowDisplayQrCode"),
        nullable=True,
    ),
    Column(
        "pix_display_qr_code",
        PaymentIntentNextActionPixDisplayQrCode,
        ForeignKey("PaymentIntentNextActionPixDisplayQrCode"),
        nullable=True,
    ),
    Column(
        "promptpay_display_qr_code",
        PaymentIntentNextActionPromptpayDisplayQrCode,
        ForeignKey("PaymentIntentNextActionPromptpayDisplayQrCode"),
        nullable=True,
    ),
    Column(
        "redirect_to_url",
        PaymentIntentNextActionRedirectToUrl,
        ForeignKey("PaymentIntentNextActionRedirectToUrl"),
        nullable=True,
    ),
    Column(
        "type",
        String,
        comment="Type of the next action to perform, one of `redirect_to_url`, `use_stripe_sdk`, `alipay_handle_redirect`, `oxxo_display_details`, or `verify_with_microdeposits`",
    ),
    Column(
        "use_stripe_sdk",
        JSON,
        comment="When confirming a PaymentIntent with Stripe.js, Stripe.js depends on the contents of this dictionary to invoke authentication flows. The shape of the contents is subject to change and is only intended to be used by Stripe.js",
        nullable=True,
    ),
    Column(
        "verify_with_microdeposits",
        PaymentIntentNextActionVerifyWithMicrodeposits,
        ForeignKey("PaymentIntentNextActionVerifyWithMicrodeposits"),
        nullable=True,
    ),
    Column(
        "wechat_pay_display_qr_code",
        PaymentIntentNextActionWechatPayDisplayQrCode,
        ForeignKey("PaymentIntentNextActionWechatPayDisplayQrCode"),
        nullable=True,
    ),
    Column(
        "wechat_pay_redirect_to_android_app",
        PaymentIntentNextActionWechatPayRedirectToAndroidApp,
        comment="[FK(PaymentIntentNextActionWechatPayRedirectToAndroidApp)]",
        nullable=True,
        primary_key=True,
    ),
    Column(
        "wechat_pay_redirect_to_ios_app",
        PaymentIntentNextActionWechatPayRedirectToIosApp,
        ForeignKey("PaymentIntentNextActionWechatPayRedirectToIosApp"),
        nullable=True,
    ),
)
__all__ = ["payment_intent_next_action.json"]
