from sqlalchemy import Column, String, Table

from . import metadata

PaymentMethodDetailsGrabpay.Json = Table(
    "payment_method_details_grabpay.json",
    metadata,
    Column(
        "transaction_id",
        String,
        comment="Unique transaction id generated by GrabPay",
        nullable=True,
        primary_key=True,
    ),
)
__all__ = ["payment_method_details_grabpay.json"]
