from sqlalchemy import Column, Identity, Integer, String

from . import Base


class PaymentMethodDetailsCardPresentReceipt(Base):
    __tablename__ = "payment_method_details_card_present_receipt"
    account_type = Column(
        String, comment="The type of account being debited or credited", nullable=True
    )
    application_cryptogram = Column(
        String,
        comment="EMV tag 9F26, cryptogram generated by the integrated circuit chip",
        nullable=True,
    )
    application_preferred_name = Column(
        String, comment="Mnenomic of the Application Identifier", nullable=True
    )
    authorization_code = Column(
        String, comment="Identifier for this transaction", nullable=True
    )
    authorization_response_code = Column(
        String, comment="EMV tag 8A. A code returned by the card issuer", nullable=True
    )
    cardholder_verification_method = Column(
        String,
        comment="How the cardholder verified ownership of the card",
        nullable=True,
    )
    dedicated_file_name = Column(
        String,
        comment="EMV tag 84. Similar to the application identifier stored on the integrated circuit chip",
        nullable=True,
    )
    terminal_verification_results = Column(
        String,
        comment="The outcome of a series of EMV functions performed by the card reader",
        nullable=True,
    )
    transaction_status_information = Column(
        String,
        comment="An indication of various EMV functions performed during the transaction",
        nullable=True,
    )
    id = Column(Integer, primary_key=True, server_default=Identity())

    def __repr__(self):
        """
        Emit a string representation of the current instance

        :return: String representation of instance
        :rtype: ```str```
        """
        return "PaymentMethodDetailsCardPresentReceipt(account_type={account_type!r}, application_cryptogram={application_cryptogram!r}, application_preferred_name={application_preferred_name!r}, authorization_code={authorization_code!r}, authorization_response_code={authorization_response_code!r}, cardholder_verification_method={cardholder_verification_method!r}, dedicated_file_name={dedicated_file_name!r}, terminal_verification_results={terminal_verification_results!r}, transaction_status_information={transaction_status_information!r}, id={id!r})".format(
            account_type=self.account_type,
            application_cryptogram=self.application_cryptogram,
            application_preferred_name=self.application_preferred_name,
            authorization_code=self.authorization_code,
            authorization_response_code=self.authorization_response_code,
            cardholder_verification_method=self.cardholder_verification_method,
            dedicated_file_name=self.dedicated_file_name,
            terminal_verification_results=self.terminal_verification_results,
            transaction_status_information=self.transaction_status_information,
            id=self.id,
        )


__all__ = ["payment_method_details_card_present_receipt"]
