from sqlalchemy import Column, ForeignKey, Identity, Integer, Table

from . import metadata

SetupAttemptPaymentMethodDetailsCardPresentJson = Table(
    "setup_attempt_payment_method_details_card_presentjson",
    metadata,
    Column(
        "generated_card",
        PaymentMethod,
        ForeignKey("PaymentMethod"),
        comment="The ID of the Card PaymentMethod which was generated by this SetupAttempt",
        nullable=True,
    ),
    Column("id", Integer, primary_key=True, server_default=Identity()),
)
__all__ = ["setup_attempt_payment_method_details_card_present.json"]
