from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    Float,
    ForeignKey,
    Integer,
    String,
    Table,
    list,
)

from stripe_openapi.account import Account
from stripe_openapi.application import Application
from stripe_openapi.customer import Customer
from stripe_openapi.discount import Discount
from stripe_openapi.invoice import Invoice

from . import metadata

SubscriptionJson = Table(
    "subscriptionjson",
    metadata,
    Column(
        "application",
        Application,
        ForeignKey("DeletedApplication"),
        comment="ID of the Connect Application that created the subscription",
        nullable=True,
    ),
    Column(
        "application_fee_percent",
        Float,
        comment="A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice subtotal that will be transferred to the application owner's Stripe account",
        nullable=True,
    ),
    Column(
        "automatic_tax",
        SubscriptionAutomaticTax,
        ForeignKey("SubscriptionAutomaticTax"),
    ),
    Column(
        "billing_cycle_anchor",
        Integer,
        comment="Determines the date of the first full invoice, and, for plans with `month` or `year` intervals, the day of the month for subsequent invoices. The timestamp is in UTC format",
    ),
    Column(
        "billing_thresholds",
        SubscriptionBillingThresholds,
        ForeignKey("SubscriptionBillingThresholds"),
        comment="Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period",
        nullable=True,
    ),
    Column(
        "cancel_at",
        Integer,
        comment="A date in the future at which the subscription will automatically get canceled",
        nullable=True,
    ),
    Column(
        "cancel_at_period_end",
        Boolean,
        comment="If the subscription has been canceled with the `at_period_end` flag set to `true`, `cancel_at_period_end` on the subscription will be true. You can use this attribute to determine whether a subscription that has a status of active is scheduled to be canceled at the end of the current period",
    ),
    Column(
        "canceled_at",
        Integer,
        comment="If the subscription has been canceled, the date of that cancellation. If the subscription was canceled with `cancel_at_period_end`, `canceled_at` will reflect the time of the most recent update request, not the end of the subscription period when the subscription is automatically moved to a canceled state",
        nullable=True,
    ),
    Column(
        "cancellation_details",
        CancellationDetails,
        ForeignKey("CancellationDetails"),
        comment="Details about why this subscription was cancelled",
        nullable=True,
    ),
    Column(
        "collection_method",
        String,
        comment="Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions and mark the subscription as `active`",
    ),
    Column(
        "created",
        Integer,
        comment="Time at which the object was created. Measured in seconds since the Unix epoch",
    ),
    Column(
        "currency",
        String,
        comment="Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies)",
    ),
    Column(
        "current_period_end",
        Integer,
        comment="End of the current period that the subscription has been invoiced for. At the end of this period, a new invoice will be created",
    ),
    Column(
        "current_period_start",
        Integer,
        comment="Start of the current period that the subscription has been invoiced for",
    ),
    Column(
        "customer",
        Customer,
        ForeignKey("DeletedCustomer"),
        comment="ID of the customer who owns the subscription",
    ),
    Column(
        "days_until_due",
        Integer,
        comment="Number of days a customer has to pay invoices generated by this subscription. This value will be `null` for subscriptions where `collection_method=charge_automatically`",
        nullable=True,
    ),
    Column(
        "default_payment_method",
        PaymentMethod,
        ForeignKey("PaymentMethod"),
        comment="ID of the default payment method for the subscription. It must belong to the customer associated with the subscription. This takes precedence over `default_source`. If neither are set, invoices will use the customer's [invoice_settings.default_payment_method](https://stripe.com/docs/api/customers/object#customer_object-invoice_settings-default_payment_method) or [default_source](https://stripe.com/docs/api/customers/object#customer_object-default_source)",
        nullable=True,
    ),
    Column(
        "default_source",
        PaymentSource,
        ForeignKey("PaymentSource"),
        comment="ID of the default payment source for the subscription. It must belong to the customer associated with the subscription and be in a chargeable state. If `default_payment_method` is also set, `default_payment_method` will take precedence. If neither are set, invoices will use the customer's [invoice_settings.default_payment_method](https://stripe.com/docs/api/customers/object#customer_object-invoice_settings-default_payment_method) or [default_source](https://stripe.com/docs/api/customers/object#customer_object-default_source)",
        nullable=True,
    ),
    Column(
        "default_tax_rates",
        list,
        comment="The tax rates that will apply to any subscription item that does not have `tax_rates` set. Invoices created will have their `default_tax_rates` populated from the subscription",
        nullable=True,
    ),
    Column(
        "description",
        String,
        comment="The subscription's description, meant to be displayable to the customer. Use this field to optionally store an explanation of the subscription for rendering in Stripe surfaces",
        nullable=True,
    ),
    Column(
        "discount",
        Discount,
        ForeignKey("Discount"),
        comment="Describes the current discount applied to this subscription, if there is one. When billing, a discount applied to a subscription overrides a discount applied on a customer-wide basis",
        nullable=True,
    ),
    Column(
        "ended_at",
        Integer,
        comment="If the subscription has ended, the date the subscription ended",
        nullable=True,
    ),
    Column("id", String, comment="Unique identifier for the object", primary_key=True),
    Column(
        "items", JSON, comment="List of subscription items, each with an attached price"
    ),
    Column(
        "latest_invoice",
        Invoice,
        ForeignKey("Invoice"),
        comment="The most recent invoice this subscription has generated",
        nullable=True,
    ),
    Column(
        "livemode",
        Boolean,
        comment="Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode",
    ),
    Column(
        "metadata",
        JSON,
        comment="Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format",
    ),
    Column(
        "next_pending_invoice_item_invoice",
        Integer,
        comment="Specifies the approximate timestamp on which any pending invoice items will be billed according to the schedule provided at `pending_invoice_item_interval`",
        nullable=True,
    ),
    Column(
        "object",
        String,
        comment="String representing the object's type. Objects of the same type share the same value",
    ),
    Column(
        "on_behalf_of",
        Account,
        ForeignKey("Account"),
        comment="The account (if any) the charge was made on behalf of for charges associated with this subscription. See the Connect documentation for details",
        nullable=True,
    ),
    Column(
        "pause_collection",
        SubscriptionsResourcePauseCollection,
        ForeignKey("SubscriptionsResourcePauseCollection"),
        comment="If specified, payment collection for this subscription will be paused",
        nullable=True,
    ),
    Column(
        "payment_settings",
        SubscriptionsResourcePaymentSettings,
        ForeignKey("SubscriptionsResourcePaymentSettings"),
        comment="Payment settings passed on to invoices created by the subscription",
        nullable=True,
    ),
    Column(
        "pending_invoice_item_interval",
        SubscriptionPendingInvoiceItemInterval,
        ForeignKey("SubscriptionPendingInvoiceItemInterval"),
        comment="Specifies an interval for how often to bill for any pending invoice items. It is analogous to calling [Create an invoice](https://stripe.com/docs/api#create_invoice) for the given subscription at the specified interval",
        nullable=True,
    ),
    Column(
        "pending_setup_intent",
        SetupIntent,
        ForeignKey("SetupIntent"),
        comment="You can use this [SetupIntent](https://stripe.com/docs/api/setup_intents) to collect user authentication when creating a subscription without immediate payment or updating a subscription's payment method, allowing you to optimize for off-session payments. Learn more in the [SCA Migration Guide](https://stripe.com/docs/billing/migration/strong-customer-authentication#scenario-2)",
        nullable=True,
    ),
    Column(
        "pending_update",
        SubscriptionsResourcePendingUpdate,
        ForeignKey("SubscriptionsResourcePendingUpdate"),
        comment="If specified, [pending updates](https://stripe.com/docs/billing/subscriptions/pending-updates) that will be applied to the subscription once the `latest_invoice` has been paid",
        nullable=True,
    ),
    Column(
        "schedule",
        SubscriptionSchedule,
        ForeignKey("SubscriptionSchedule"),
        comment="The schedule attached to the subscription",
        nullable=True,
    ),
    Column(
        "start_date",
        Integer,
        comment="Date when the subscription was first created. The date might differ from the `created` date due to backdating",
    ),
    Column(
        "status",
        String,
        comment="Possible values are `incomplete`, `incomplete_expired`, `trialing`, `active`, `past_due`, `canceled`, or `unpaid`. \n\nFor `collection_method=charge_automatically` a subscription moves into `incomplete` if the initial payment attempt fails. A subscription in this state can only have metadata and default_source updated. Once the first invoice is paid, the subscription moves into an `active` state. If the first invoice is not paid within 23 hours, the subscription transitions to `incomplete_expired`. This is a terminal state, the open invoice will be voided and no further invoices will be generated. \n\nA subscription that is currently in a trial period is `trialing` and moves to `active` when the trial period is over. \n\nIf subscription `collection_method=charge_automatically` it becomes `past_due` when payment to renew it fails and `canceled` or `unpaid` (depending on your subscriptions settings) when Stripe has exhausted all payment retry attempts. \n\nIf subscription `collection_method=send_invoice` it becomes `past_due` when its invoice is not paid by the due date, and `canceled` or `unpaid` if it is still not paid by an additional deadline after that. Note that when a subscription has a status of `unpaid`, no subsequent invoices will be attempted (invoices will be created, but then immediately automatically closed). After receiving updated payment information from a customer, you may choose to reopen and pay their closed invoices",
    ),
    Column(
        "test_clock",
        Test_Helpers__TestClock,
        ForeignKey("Test_Helpers__TestClock"),
        comment="ID of the test clock this subscription belongs to",
        nullable=True,
    ),
    Column(
        "transfer_data",
        SubscriptionTransferData,
        ForeignKey("SubscriptionTransferData"),
        comment="The account (if any) the subscription's payments will be attributed to for tax reporting, and where funds from each payment will be transferred to for each of the subscription's invoices",
        nullable=True,
    ),
    Column(
        "trial_end",
        Integer,
        comment="If the subscription has a trial, the end of that trial",
        nullable=True,
    ),
    Column(
        "trial_settings",
        SubscriptionsTrialsResourceTrialSettings,
        ForeignKey("SubscriptionsTrialsResourceTrialSettings"),
        comment="Settings related to subscription trials",
        nullable=True,
    ),
    Column(
        "trial_start",
        Integer,
        comment="If the subscription has a trial, the beginning of that trial",
        nullable=True,
    ),
)
__all__ = ["subscription.json"]
